DROP USER SQLD CASCADE;
DROP TABLESPACE SQLD_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE SQLD_TEMP INCLUDING CONTENTS AND DATAFILES;

CREATE USER SQLD IDENTIFIED BY 1234;
ALTER USER SQLD ACCOUNT UNLOCK;
GRANT RESOURCE, DBA, CONNECT TO SQLD;

CREATE TABLESPACE SQLD_DATA
datafile 'C:\app\dbmsexpert\virtual\oradata\orcl12cr2\SQLD_DATA.dbf' SIZE 1G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
CREATE TEMPORARY TABLESPACE SQLD_TEMP
TEMPFILE 'C:\app\dbmsexpert\virtual\oradata\orcl12cr2\SQLD_TEMP.dbf' SIZE 512M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER SQLD DEFAULT TABLESPACE SQLD_DATA;
ALTER USER SQLD TEMPORARY TABLESPACE SQLD_TEMP;