create table tb_account_transaction_test (
	id int generated by default as identity,
	name varchar(100) not null,
	balance dec(15, 2) not null,
	primary key(id)
	);
	
commit;

BEGIN;
INSERT INTO TB_ACCOUNT_TRANSACTION_TEST
(NAME,BALANCE)
VALUES('Alice',10000);
COMMIT;

INSERT INTO TB_ACCOUNT_TRANSACTION_TEST
(NAME,BALANCE)
VALUES('Danny',20000);

ROLLBACK;